### ISSUE TITLE
Fails to build on OS X 10.11/El Capitan

### ISSUE THREAD

**Issue by DomT4** [xicilion/fibjs#96]
Error is:

```
Scanning dependencies of target snappy
[ 20%] Building CXX object CMakeFiles/snappy.dir/src/snappy-c.cc.o
[ 40%] Building CXX object CMakeFiles/snappy.dir/src/snappy-sinksource.cc.o
[ 60%] Building CXX object CMakeFiles/snappy.dir/src/snappy-stubs-internal.cc.o
[ 80%] Building CXX object CMakeFiles/snappy.dir/src/snappy.cc.o
[100%] Linking CXX static library /tmp/fibjs20150914-1068-1rzgov0/bin/Darwin_Release/vender/libsnappy.a
[100%] Built target snappy
Scanning dependencies of target ev
[ 50%] Building C object CMakeFiles/ev.dir/src/ev.c.o
/tmp/fibjs20150914-1068-1rzgov0/vender/ev/src/ev.c:970:42: error: '_Noreturn' keyword must precede function declarator
  ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                         ^~~~~~~~~~~~
  _Noreturn
/tmp/fibjs20150914-1068-1rzgov0/vender/ev/src/ev.c:773:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
1 error generated.
make[2]: *** [CMakeFiles/ev.dir/src/ev.c.o] Error 1
make[1]: *** [CMakeFiles/ev.dir/all] Error 2
make: *** [all] Error 2
```

Failure to compile still against the master (https://github.com/xicilion/fibjs/commit/01798425965d81fa0bc0976be5b96d3ccbfb84e1) here & was reported to Homebrew in https://github.com/Homebrew/homebrew/issues/42490.

Configuration tested is:

```
OS X: 10.11-x86_64
Xcode: 7.0
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
```

**Comment by xicilion** [comment]
thanks report, I'm working on it.

**Comment by xicilion** [comment]
fixed.
